routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes(['register' => false, 'reset' => false]);
//demo
Route::get('demo','DemoController@index');
Route::get('demodashboard','DemoController@demodashboard')->name('demodashboard');
Route::get('companyprofile','DemoController@companyprofile')->name('companyprofile');
Route::get('myprofile','DemoController@myprofile')->name('myprofile');
Route::get('users','DemoController@users')->name('users');
Route::get('demoproperty','DemoController@property')->name('demoproperty');
//
Route::group(['middleware' => 'auth'], function () {

    Route::namespace('Admin')->group(function () {
        Route::resource('admin/roles', 'AdminRolesController');
        Route::resource('admin/users', 'AdminUsersController');




    Route::resource('admin/associations', 'AdminAssociationsController');
        Route::get('riapermissions/{id}', ['as'=> 'roles.riapermissions','uses' => 'RiaPermissionController@index']);
        Route::put('riapermissions/{id}', ['as'=> 'roles.riapermissions.update','uses' => 'RiaPermissionController@update']);

        Route::resource('admin/location/country', 'AdminCountriesController');
        Route::resource('admin/location/zone', 'AdminZoneController');
        Route::resource('admin/location/city', 'AdminCityController');
        Route::resource('admin/location/community', 'AdminCommunityController');
        Route::resource('admin/location/subcommunity', 'AdminSubCommunityController');
        Route::resource('admin/email/campaign', 'AdminCampaignsController');
        Route::resource('admin/email/template', 'AdminEmailTemplateController');
        Route::resource('products', 'AdminProductsController');
        Route::resource('inclusions', 'AdminInclusionsController');
        Route::resource('cmscategories', 'AdminCmsCategories');
        Route::resource('cms', 'AdminCms');
        Route::resource('seo', 'AdminSeoManagement');
        Route::resource('admin/propertyfeild', 'AdminPropertyFeild');
        Route::resource('admin/propertyfeildlist', 'AdminPropertyFeildList');
        Route::resource('admin/setting', 'AdminSettings');
        Route::resource('property', 'AdminProperty');
        Route::resource('project', 'AdminProject');
        //Package Management
        Route::get('agentpackage', 'AdminPackagesController@index')->name('agentpackage');
        Route::get('companypackage', 'AdminPackagesController@companyPackage')->name('companypackage');
        Route::get('developerpackage', 'AdminPackagesController@developerPackage')->name('developerpackage');
        Route::get('corporateaffiliatepackage', 'AdminPackagesController@corporateAffiliatePackage')->name('corporateaffiliatepackage');
        Route::post('updatepackage', 'AdminPackagesController@updatepackage')->name('updatepackage');
        //get location for dropdown
        Route::get('admin/location/getCountries', 'AdminCountriesController@getCountries')->name('getCountries');
        Route::post('admin/location/getZonesbyId', 'AdminZoneController@getZonesbyId')->name('getZonesbyId');
        Route::post('admin/location/getCitiesbyId', 'AdminCityController@getCitiesbyId')->name('getCitiesbyId');
        Route::post('admin/location/getCommunitybyId', 'AdminCommunityController@getCommunitybyId')->name('getCommunitybyId');
        Route::post('cmscategories/storeCategoryFromAjax', 'AdminCmsCategories@storeCategoryFromAjax')->name('storeCategoryFromAjax');
        //statusChange routes
        Route::get('roles/statusChange/{id}', ['as'=> 'roles.statusChange','uses' => 'AdminRolesController@statusChange']);
        Route::get('associations/statusChange/{id}', ['as'=> 'associations.statusChange','uses' => 'AdminAssociationsController@statusChange']);
        Route::get('location/country/statusChange/{id}', ['as'=> 'country.statusChange','uses' => 'AdminCountriesController@statusChange']);
        Route::get('location/zone/statusChange/{id}', ['as'=> 'zone.statusChange','uses' => 'AdminZoneController@statusChange']);
        Route::get('location/city/statusChange/{id}', ['as'=> 'city.statusChange','uses' => 'AdminCityController@statusChange']);
        Route::get('location/community/statusChange/{id}', ['as'=> 'community.statusChange','uses' => 'AdminCommunityController@statusChange']);
        Route::get('location/subcommunity/statusChange/{id}', ['as'=> 'subcommunity.statusChange','uses' => 'AdminSubCommunityController@statusChange']);
        Route::get('products/statusChange/{id}', ['as'=> 'products.statusChange','uses' => 'AdminProductsController@statusChange']);
        Route::get('inclusions/statusChange/{id}', ['as'=> 'inclusions.statusChange','uses' => 'AdminInclusionsController@statusChange']);
        Route::get('users/statusChange/{id}', ['as'=> 'users.statusChange','uses' => 'AdminUsersController@statusChange']);
        Route::get('email/campaign/statusChange/{id}', ['as'=> 'campaign.statusChange','uses' => 'AdminCampaignsController@statusChange']);
        Route::get('email/campaign/template/{id}', ['as'=> 'template.statusChange','uses' => 'AdminEmailtemplateController@statusChange']);
        Route::get('seo/seo/{id}', ['as'=> 'seo.statusChange','uses' => 'AdminSeoManagement@statusChange']);
        Route::get('propertyfeild/propertyfeild/{id}', ['as'=> 'propertyfeild.statusChange','uses' => 'AdminPropertyFeild@statusChange']);
        Route::get('propertyfeildlist/propertyfeildlist/{id}', ['as'=> 'propertyfeildlist.statusChange','uses' => 'AdminPropertyFeildList@statusChange']);

        Route::get('cms/cmscategory/{id}', ['as'=> 'cmscategory.statusChange','uses' => 'AdminCmsCategories@statusChange']);
        Route::get('cms/cms/{id}', ['as'=> 'cms.statusChange','uses' => 'AdminCms@statusChange']);
        Route::get('setting/setting/{id}', ['as'=> 'setting.statusChange','uses' => 'AdminSettings@statusChange']);
        Route::get('property/property/{id}', ['as'=> 'property.statusChange','uses' => 'AdminProperty@statusChange']);
        //Route::get('project/project/{id}', ['as'=> 'project.statusChange','uses' => 'AdminProject@statusChange']);

        Route::get('products/timePricesDelete/{id}', ['as'=> 'products.timePricesDelete','uses' => 'AdminProductsController@timePricesDelete']);

        Route::post('users/checkParentRole', ['as'=> 'users.checkParentRole','uses' => 'AdminUsersController@checkParentRole']);
    });
    Route::group(['namespace' => 'Admin','as'=>'admin'], function () {
        Route::get('/dashboard', 'Dashboard@index')->name('dashboard');
    });
});

app/Zone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Zone extends Model
{
    //
    protected $fillable = ['name','code','latitude','longitude','description','image','created_by','updated_by','country'];

    public function users(){
        return $this->hasMany('App\User','zone');
    }

    public function countryDet(){
        return $this->belongsTo('App\Country','country');
    }
}

resources/views/admin/location/zone/form.blade.php
@extends('layouts.admin')
@section('content')

<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-12 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">   Locations
                        <small>Manage Zones</small></h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('/dashboard')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('zone.index')}}">Zone</a></li>
                            <li class="breadcrumb-item active"><a href="">Add/Edit</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section id="basic-horizontal-layouts">
            <div class="row">
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-body">
                                @if(isset($zone->id)) {{--edit form--}}
                                <form method="POST"
                                action="{{route('zone.update',$zone->id)}}"
                                name="zoneForm"
                                id="zoneForm"
                                class="form form-vertical"
                                enctype="multipart/form-data">
                                {{csrf_field()}}
                                {{ method_field('PUT') }}
                                @else
                                <form method="POST"
                                            action="{{route('zone.store')}}"
                                            name="zoneForm"
                                            id="zoneForm"
                                            class="form form-vertical"
                                            enctype="multipart/form-data">  {{csrf_field()}}
                                @endif
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" value="{{$zone->name}}" class="form-control" data-validation="required">

                                </div>
                                <div class="form-group">
                                        <label>Code</label>
                                        <input type="text" name="code" value="{{$zone->code}}" class="form-control" data-validation="required">
                                </div>
                                <div class="form-group">
                                    <label>Country</label>
                                    <select name="country" class="form-control" name="country">
                                        <option value="" @if($zone->country == '') selected @endif>Select Country</option>
                                        @foreach ($countries as $country)
                                        <option value="{{$country->id}}" @if($zone->country == $country->id) selected @endif>{{$country->name}}</option>
                                    @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Latitude</label>
                                    <input type="text" name="latitude" value="{{$zone->latitude}}" class="form-control" data-validation="required">
                                </div>
                                <div class="form-group">
                                    <label>Longitude</label>
                                    <input type="text" name="longitude" value="{{$zone->longitude}}" class="form-control" data-validation="required">
                                </div>
                                <button class="btn btn-primary">Save</button>
                                <a href="{{route('zone.index')}}" class="btn btn-default">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/admin/location/zone/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Location
                        <small>Manage Zones</small></h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('/dashboard')}}">Home</a></li>
                            <li class="breadcrumb-item active"><a href="{{route('zone.index')}}">Zones</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-body">
        <div class="card-content">
            <div class="data-list-view-header">
                <div class="card filter">
                    <div class="card-header">
                        <h4 class="card-title">Filters</h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="feather icon-chevron-down"></i></a></li>
                                <li><a href="{{route('zone.index')}}"><i class="feather icon-rotate-cw users-data-filter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="users-list-filter">
                                <form method="GET" action="{{route('zone.index')}}">
                                    <div class="row">
                                        <div class="col-12 col-sm-6 col-lg-3">
                                            <label for="users-list-role">Country</label>
                                            <fieldset class="form-group">
                                               <select name="country" class="form-control">
                                                   <option value="">Select Country</option>
                                                   @foreach ($countries as $countrie)
                                                       <option value="{{$countrie->id}}">{{$countrie->name}}</option>
                                                   @endforeach
                                               </select>
                                            </fieldset>
                                        </div>

                                        <div class="col-12 col-sm-6 col-lg-3">
                                            <label for="users-list-role">Name</label>
                                            <fieldset class="form-group">
                                               <input type="text" class="form-control" value="{{app('request')->input('name')}}" name="name">
                                            </fieldset>
                                        </div>
                                        {{-- <div class="col-12 col-sm-6 col-lg-3">
                                            <label for="users-list-status">Status</label>
                                            <fieldset class="form-group">
                                                <select class="form-control" id="users-list-status">
                                                    <option value="">All</option>
                                                    <option value="Active">Active</option>
                                                    <option value="Blocked">Blocked</option>
                                                    <option value="deactivated">Deactivated</option>
                                                </select>
                                            </fieldset>
                                        </div> --}}
                                        <div class="col-12 col-sm-6 col-lg-3">
                                            <label for="users-list-role"></label>
                                        <button class="btn btn-primary search" type="submit"><i class="feather icon-search"></i> Search</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 noapd">
                    <div class="form-group">
                        <a class="btn btn-primary" href="{{ route("zone.create") }}"><i class="feather icon-plus"></i> Zone</a>
                    </div>
                    </div>
                    @if(Session::has('success_msg'))
                        <div class="col-md-12 noapd">
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <p><i class="icon fa fa-check"></i> {{session('success_msg')}}</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        </div>
                    @endif
                    @if(Session::has('fail_msg'))
                        <div class="col-md-12 noapd">
                        <div class="alert alert-danger alert-dismissible">

                            <p><i class="icon fa fa-ban"></i> {{session('fail_msg')}}</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        </div>
                    @endif
            <div class="table-responsive mt-1">
                <div class="dataTables_wrapper dt-bootstrap4 no-footer">
                <table class="table table-hover-animation mb-0">
                    <thead>
                        <tr>
                            <th style="width:2%">Sl.no</th>
                            <th >Action</th>
                            <th>Name</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                            <th>Code</th>
                            <th>Country</th>
                            <th>Created Date</th>
                            <th>Modified Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($zones)
                            @if($zones->currentpage() == 1)
                                @php($ctr = 1)
                            @else
                                @php($ctr = ($zones->currentpage()-1)*$zones->perpage()+1)

                            @endif
                            @if($zones->count() > 0)
                                @foreach($zones as $zone)

                                    <tr>
                                        <td >{{$ctr}}</td>
                                        <td>
                                            <span style="float: left"><a href="{{route('zone.edit',$zone->id)}}" data-toggle="tooltip" title="Edit"><i class="feather icon-edit"></i></a></span>

                                            <span style="float: left">
                                        <form action="{{route('zone.destroy',$zone->id) }}" method="post" id="deleteForm{{$zone->id}}">
                                            <input type="hidden" name="_method" value="DELETE">
                                            {!! csrf_field() !!}
                                            <a href="javascript:void(0)" onclick="document.getElementById('deleteForm{{$zone->id}}').submit();" data-toggle="tooltip" title="Delete">
                                                <i class="feather icon-trash"></i></a>

                                        </form>
                                        </span>

                                            @if($zone->is_active)
                                                <span><a href="{{route('zone.statusChange',$zone->id)}}" data-toggle="tooltip" title="Click to Disable">
                                                        <span style="color: yellowgreen"><i class="feather icon-check"></i></span></a></span>
                                            @else
                                                <span><a href="{{route('zone.statusChange',$zone->id)}}" data-toggle="tooltip" title="Click to Enable">
                                                        <span style="color: red"><i class="feather icon-x"></i></span></a></span>
                                            @endif

                                        </td>
                                        <td>{{$zone->name}} </td>
                                        <td>{{$zone->latitude}} </td>
                                        <td>{{$zone->longitude}} </td>
                                        <td>{{$zone->code}} </td>
                                        <td>{{$zone->countryDet->name}} </td>
                                        <td>{{$zone->created_at->format('Y-m-d')}}</td>
                                        <td>{{$zone->updated_at->format('Y-m-d')}}</td>
                                    </tr>
                                    @php($ctr++)
                                @endforeach
                            @else
                                <tr><td colspan="10" style="text-align: center">No records available</td></tr>
                            @endif
                        @endif
                        </tbody>
                </table>
                </div>
                @include('admin/partials/pagination',['results'=>$zones])

            </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/location/zone/view.blade.php
@extends('layouts.admin')
@section('content')
    
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Locations
                <small>Manage Zones</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{route('zone.index')}}">Zone</a></li>
                <li class="active">View</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                <div class="box box-primary viewform" style="padding:20px;float: left;">
                    <div class="form-group">
                        <label>Name :</label><span>{{$zone->name}}</span>
                    </div>
                   
                    <div class="form-group">
                        <label>ISO Code 3 :</label><span>{{$zone->code}}</span>
                    </div>
                    <div class="form-group">
                        <label>Country :</label><span>{{$zone->countryDet->name}} </span>
                    </div>
                    <div class="form-group">
                        <label>Latitude :</label><span>{{$zone->latitude}}</span>
                    </div>
                    <div class="form-group">
                        <label>Longitude :</label><span>{{$zone->longitude}}</span>
                    </div>
                    <div class="form-group">
                        <label>Description :</label><span>{{$zone->description}}</span>
                    </div>
                    <div class="form-group">
                        <label>Image :</label>
                        @if($zone->image)
                        <span class="w100"><img src="{{ url('/') }}{{$zone->image}}" style="width:100px"></span>
                        @endif
                    </div>
                    
                   
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
    </div>
@stop