routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes(['register' => false, 'reset' => false]);
//demo
Route::get('demo','DemoController@index');
Route::get('demodashboard','DemoController@demodashboard')->name('demodashboard');
Route::get('companyprofile','DemoController@companyprofile')->name('companyprofile');
Route::get('myprofile','DemoController@myprofile')->name('myprofile');
Route::get('users','DemoController@users')->name('users');
Route::get('demoproperty','DemoController@property')->name('demoproperty');
//
Route::group(['middleware' => 'auth'], function () {

    Route::namespace('Admin')->group(function () {
        Route::resource('admin/roles', 'AdminRolesController');
        Route::resource('admin/users', 'AdminUsersController');




    Route::resource('admin/associations', 'AdminAssociationsController');
        Route::get('riapermissions/{id}', ['as'=> 'roles.riapermissions','uses' => 'RiaPermissionController@index']);
        Route::put('riapermissions/{id}', ['as'=> 'roles.riapermissions.update','uses' => 'RiaPermissionController@update']);

        Route::resource('admin/location/country', 'AdminCountriesController');
        Route::resource('admin/location/zone', 'AdminZoneController');
        Route::resource('admin/location/city', 'AdminCityController');
        Route::resource('admin/location/community', 'AdminCommunityController');
        Route::resource('admin/location/subcommunity', 'AdminSubCommunityController');
        Route::resource('admin/email/campaign', 'AdminCampaignsController');
        Route::resource('admin/email/template', 'AdminEmailTemplateController');
        Route::resource('products', 'AdminProductsController');
        Route::resource('inclusions', 'AdminInclusionsController');
        Route::resource('cmscategories', 'AdminCmsCategories');
        Route::resource('cms', 'AdminCms');
        Route::resource('seo', 'AdminSeoManagement');
        Route::resource('admin/propertyfeild', 'AdminPropertyFeild');
        Route::resource('admin/propertyfeildlist', 'AdminPropertyFeildList');
        Route::resource('admin/setting', 'AdminSettings');
        Route::resource('property', 'AdminProperty');
        Route::resource('project', 'AdminProject');
        //Package Management
        Route::get('agentpackage', 'AdminPackagesController@index')->name('agentpackage');
        Route::get('companypackage', 'AdminPackagesController@companyPackage')->name('companypackage');
        Route::get('developerpackage', 'AdminPackagesController@developerPackage')->name('developerpackage');
        Route::get('corporateaffiliatepackage', 'AdminPackagesController@corporateAffiliatePackage')->name('corporateaffiliatepackage');
        Route::post('updatepackage', 'AdminPackagesController@updatepackage')->name('updatepackage');
        //get location for dropdown
        Route::get('admin/location/getCountries', 'AdminCountriesController@getCountries')->name('getCountries');
        Route::post('admin/location/getZonesbyId', 'AdminZoneController@getZonesbyId')->name('getZonesbyId');
        Route::post('admin/location/getCitiesbyId', 'AdminCityController@getCitiesbyId')->name('getCitiesbyId');
        Route::post('admin/location/getCommunitybyId', 'AdminCommunityController@getCommunitybyId')->name('getCommunitybyId');
        Route::post('cmscategories/storeCategoryFromAjax', 'AdminCmsCategories@storeCategoryFromAjax')->name('storeCategoryFromAjax');
        //statusChange routes
        Route::get('roles/statusChange/{id}', ['as'=> 'roles.statusChange','uses' => 'AdminRolesController@statusChange']);
        Route::get('associations/statusChange/{id}', ['as'=> 'associations.statusChange','uses' => 'AdminAssociationsController@statusChange']);
        Route::get('location/country/statusChange/{id}', ['as'=> 'country.statusChange','uses' => 'AdminCountriesController@statusChange']);
        Route::get('location/zone/statusChange/{id}', ['as'=> 'zone.statusChange','uses' => 'AdminZoneController@statusChange']);
        Route::get('location/city/statusChange/{id}', ['as'=> 'city.statusChange','uses' => 'AdminCityController@statusChange']);
        Route::get('location/community/statusChange/{id}', ['as'=> 'community.statusChange','uses' => 'AdminCommunityController@statusChange']);
        Route::get('location/subcommunity/statusChange/{id}', ['as'=> 'subcommunity.statusChange','uses' => 'AdminSubCommunityController@statusChange']);
        Route::get('products/statusChange/{id}', ['as'=> 'products.statusChange','uses' => 'AdminProductsController@statusChange']);
        Route::get('inclusions/statusChange/{id}', ['as'=> 'inclusions.statusChange','uses' => 'AdminInclusionsController@statusChange']);
        Route::get('users/statusChange/{id}', ['as'=> 'users.statusChange','uses' => 'AdminUsersController@statusChange']);
        Route::get('email/campaign/statusChange/{id}', ['as'=> 'campaign.statusChange','uses' => 'AdminCampaignsController@statusChange']);
        Route::get('email/campaign/template/{id}', ['as'=> 'template.statusChange','uses' => 'AdminEmailtemplateController@statusChange']);
        Route::get('seo/seo/{id}', ['as'=> 'seo.statusChange','uses' => 'AdminSeoManagement@statusChange']);
        Route::get('propertyfeild/propertyfeild/{id}', ['as'=> 'propertyfeild.statusChange','uses' => 'AdminPropertyFeild@statusChange']);
        Route::get('propertyfeildlist/propertyfeildlist/{id}', ['as'=> 'propertyfeildlist.statusChange','uses' => 'AdminPropertyFeildList@statusChange']);

        Route::get('cms/cmscategory/{id}', ['as'=> 'cmscategory.statusChange','uses' => 'AdminCmsCategories@statusChange']);
        Route::get('cms/cms/{id}', ['as'=> 'cms.statusChange','uses' => 'AdminCms@statusChange']);
        Route::get('setting/setting/{id}', ['as'=> 'setting.statusChange','uses' => 'AdminSettings@statusChange']);
        Route::get('property/property/{id}', ['as'=> 'property.statusChange','uses' => 'AdminProperty@statusChange']);
        //Route::get('project/project/{id}', ['as'=> 'project.statusChange','uses' => 'AdminProject@statusChange']);

        Route::get('products/timePricesDelete/{id}', ['as'=> 'products.timePricesDelete','uses' => 'AdminProductsController@timePricesDelete']);

        Route::post('users/checkParentRole', ['as'=> 'users.checkParentRole','uses' => 'AdminUsersController@checkParentRole']);
    });
    Route::group(['namespace' => 'Admin','as'=>'admin'], function () {
        Route::get('/dashboard', 'Dashboard@index')->name('dashboard');
    });
});

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.1.0
    </div>
    <strong>Copyright  2018 <a href="https://realopedia.com">Realopedia</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/partials/header.blade.php
<header class="main-header">
<!-- Logo -->
<a href="dashboard" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">Realopedia</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Realopedia</b></span>
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->
            <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-envelope-o"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 4 messages</li>
                    <li>
                        <!-- inner menu: contains the actual data -->
                        <ul class="menu">
                            <li><!-- start message -->
                                <a href="#">
                                    <div class="pull-left">
                                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    </div>
                                    <h4>
                                        Support Team
                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                    </h4>
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                            </li>
                            <!-- end message -->
                            <li>
                                <a href="#">
                                    <div class="pull-left">
                                        <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                                    </div>
                                    <h4>
                                        AdminLTE Design Team
                                        <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                    </h4>
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="pull-left">
                                        <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                                    </div>
                                    <h4>
                                        Developers
                                        <small><i class="fa fa-clock-o"></i> Today</small>
                                    </h4>
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
            </li>
            <!-- Notifications: style can be found in dropdown.less -->
            <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 10 notifications</li>
                    <li>
                        <!-- inner menu: contains the actual data -->
                        <ul class="menu">
                            <li>
                                <a href="#">
                                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                                    page and may cause design problems
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li class="footer"><a href="#">View all</a></li>
                </ul>
            </li>

            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="hidden-xs">{{$user->contact_name}}</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                        <img src="{{ $user->user_image ? asset('storage/images/users/'.$user->user_image) : asset('storage/images/users/noimage.png') }}"
                             class="img-circle" alt="">
                        <p>
                            <small>{{ucfirst($user->role->title)}} Account</small>
                        </p>
                    </li>

                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href=" {{ route('logout') }} "
                               onclick="event.preventDefault();document.getElementById('logout-form').submit();"
                               class="btn btn-default btn-flat">Sign out</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                </ul>
            </li>

        </ul>
    </div>
</nav>
</header>

resources/views/admin/partials/pagination.blade.php
<style>
    .pagination {
	justify-content: center;
}
</style>
<div id="page1-content" class="border-grey border-lighten-2 p-1 mb-1" style="background: #fff;text-align: center;margin-top: 10px;">Showing {{($results->currentpage()-1)*$results->perpage()+1}} to
    {{($results->currentpage()-1)*$results->perpage()+$results->count()}}
    of  {{$results->total()}} entries</div>

    <div class="text-center">
        {{ $results->render() }}
    </div>

resources/views/admin/partials/sidemenu.blade.php
<!-- sidebar: style can be found in sidebar.less -->
<aside class="main-sidebar">
<section class="sidebar">
    <ul class="sidebar-menu" data-widget="tree">
        <li class="active">
            <a href="{{url('/admin/dashboard')}}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>
        @can('accessPermission','user,role,association')
        <li class="treeview">
            <a href="#">
                <i class="fa  fa-user"></i>
                <span>User Management</span>
                <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                @can('accessPermission','role')
                <li><a href="{{route('roles.index')}}"><i class="fa fa-circle-o"></i> Roles</a></li>
                @endcan
                @can('accessPermission','association')
                <li><a href="{{route('associations.index')}}"><i class="fa fa-circle-o"></i> Associations/Groups</a></li>
                @endcan
                @can('accessPermission','user')
                <li><a href="{{route('users.index')}}"><i class="fa fa-circle-o"></i> Users</a></li>
                @endcan
            </ul>
        </li>
        @endcan
        @can('accessPermission','location')
        <li class="treeview">
            <a href="#">
                <i class="fa  fa-map-marker"></i>
                <span>Location Management</span>
                <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="{{route('country.index')}}"><i class="fa fa-circle-o"></i> Country</a></li>
                <li><a href="{{route('zone.index')}}"><i class="fa fa-circle-o"></i> Zone</a></li>
                <li><a href="{{route('city.index')}}"><i class="fa fa-circle-o"></i> City</a></li>
                <li><a href="{{route('community.index')}}"><i class="fa fa-circle-o"></i> Community</a></li>
                <li><a href="{{route('subcommunity.index')}}"><i class="fa fa-circle-o"></i> Subcommunity</a></li>
            </ul>
        </li>
        @endcan
        @can('accessPermission',['product','inclusion'])
        <li class="treeview">
            <a href="#">
                <i class="fa fa-suitcase"></i>
                <span>Products Management</span>
                <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
            </a>

            <ul class="treeview-menu">
                @can('accessPermission','product')
                <li><a href="{{route('products.index')}}"><i class="fa fa-circle-o"></i>Products</a></li>
                @endcan
                @can('accessPermission','inclusion')
                <li><a href="{{route('inclusions.index')}}"><i class="fa fa-circle-o"></i>Inclusions</a></li>
                @endcan
                {{--<li><a href="{{route('productIncludes.index')}}"><i class="fa fa-circle-o"></i> Product Includes</a></li>--}}
            </ul>
        </li>
        @endcan
        @can('accessPermission','package')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-server"></i>
                    <span>Packages Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('agentpackage')}}"><i class="fa fa-circle-o"></i> Agent Packages</a></li>
                    <li><a href="{{route('companypackage')}}"><i class="fa fa-circle-o"></i> Company Packages</a></li>
                    <li><a href="{{route('developerpackage')}}"><i class="fa fa-circle-o"></i> Developer Packages</a></li>
                    <li><a href="{{route('corporateaffiliatepackage')}}"><i class="fa fa-circle-o"></i> Corporate Affiliate Packages</a></li>
                </ul>
            </li>
        @endcan
        @can('accessPermission',['email'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-envelope-o"></i>
                    <span>Email Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                        <li><a href="{{route('campaign.index')}}"><i class="fa fa-circle-o"></i>Campaigns</a></li>
                        <li><a href="{{route('template.index')}}"><i class="fa fa-circle-o"></i>Email Templates</a></li>
                        <li><a href="{{route('inclusions.index')}}"><i class="fa fa-circle-o"></i>Schedules</a></li>
                    {{--<li><a href="{{route('productIncludes.index')}}"><i class="fa fa-circle-o"></i> Product Includes</a></li>--}}
                </ul>
            </li>
        @endcan
        @can('accessPermission',['cms'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-television"></i>
                    <span>CMS Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                        @can('accessPermission',['cms_category'])
                        <li><a href="{{route('cmscategories.index')}}"><i class="fa fa-circle-o"></i>CMS Category</a></li>
                        @endcan
                        <li><a href="{{route('cms.index')}}"><i class="fa fa-circle-o"></i>CMS Listing</a></li>
                        
                </ul>
            </li>
        @endcan
        @can('accessPermission',['seo'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-television"></i>
                    <span>SEO Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                        
                        <li><a href="{{route('seo.index')}}"><i class="fa fa-circle-o"></i>SEO</a></li>
                        
                        
                </ul>
            </li>
        @endcan
        @can('accessPermission',['propertyfeild'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-television"></i>
                    <span>Property Options</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                        
                        <li><a href="{{route('propertyfeild.index')}}"><i class="fa fa-circle-o"></i>Property Feilds</a></li>
                        <li><a href="{{route('propertyfeildlist.index')}}"><i class="fa fa-circle-o"></i>Property Feild List</a></li>
                        
                </ul>
            </li>
        @endcan
        @can('accessPermission',['property'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-building"></i>
                    <span>Property</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('property.index')}}"><i class="fa fa-circle-o"></i>Property</a></li>
                </ul>
            </li>
        @endcan
        @can('accessPermission',['project'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-building"></i>
                    <span>Project</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('project.index')}}"><i class="fa fa-circle-o"></i>Project</a></li>
                </ul>
            </li>
        @endcan

        @can('accessPermission',['setting'])
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-fw fa-gear"></i>
                    <span>Settings</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('setting.index')}}"><i class="fa fa-circle-o"></i>Keys And Code</a></li>
                </ul>
            </li>
        @endcan
    </ul>
</section>
<!-- /.sidebar -->
</aside>